### ISSUE TITLE
Stale Element Reference Exception

### ISSUE THREAD

**Issue by jvervaec** [darcy-framework/darcy-webdriver#42]
Seems to happen during waitUpTo for the same page object several times in a test, like at the start of a helper method.

isDisplayed (and IsPresent) don't use attempt to catch this exception.

https://github.com/darcy-framework/darcy-webdriver/blob/master/src/main/java/com/redhat/darcy/webdriver/elements/WebDriverElement.java#L67

Partial stack trace
Caused by: org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
...
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:320)
	at com.redhat.darcy.webdriver.internal.TargetedWebElement.isDisplayed(TargetedWebElement.java:116)
	at com.redhat.darcy.webdriver.elements.WebDriverElement.isDisplayed(WebDriverElement.java:69)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.darcy.ui.internal.ElementHandler.invoke(ElementHandler.java:81)
	at com.sun.proxy.$Proxy28.isDisplayed(Unknown Source)
	at com.redhat.darcy.salesforce.RelatedList.isLoaded(RelatedList.java:98)
	at com.redhat.darcy.ui.matchers.ViewIsLoaded.matchesSafely(ViewIsLoaded.java:30)
	at com.redhat.darcy.ui.matchers.ViewIsLoaded.matchesSafely(ViewIsLoaded.java:1)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at com.redhat.darcy.ui.matchers.LoadConditionMatcher.doesItemMatchAppropriateCondition(LoadConditionMatcher.java:91)
	at com.redhat.darcy.ui.matchers.LoadConditionMatcher.matches(LoadConditionMatcher.java:44)
	at com.redhat.synq.HamcrestCondition.isMet(HamcrestCondition.java:80)
	at com.redhat.darcy.ui.AbstractView$$Lambda$51/260466839.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at com.redhat.darcy.ui.AbstractView.isLoaded(AbstractView.java:101)
	at com.redhat.darcy.ui.matchers.ViewIsLoadedInContext.matchesSafely(ViewIsLoadedInContext.java:39)
	at com.redhat.darcy.ui.matchers.ViewIsLoadedInContext.matchesSafely(ViewIsLoadedInContext.java:1)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at com.redhat.synq.HamcrestCondition.isMet(HamcrestCondition.java:80)
	at com.redhat.synq.ThreadedPollEvent$$Lambda$36/480184864.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by alechenninger** [comment]
Fixed in #44
