### ISSUE TITLE
Exception transitioning to view in new context

### ISSUE THREAD

**Issue by jvervaec** [darcy-framework/darcy-webdriver#53]
Given
Synq.after(someElement::click)
                .expect(transition().to(new View()).inNewContext())            
                .waitUpTo(10, ChronoUnit.SECONDS);

Throws
com.redhat.darcy.ui.DarcyException: Cannot find contexts of type: interface com.redhat.darcy.ui.api.FindableElementContext
	at com.redhat.darcy.webdriver.internal.TargetedWebDriverParentContext.findByView(TargetedWebDriverParentContext.java:112)
	at com.redhat.darcy.webdriver.internal.DelegatingWebContext.findByView(DelegatingWebContext.java:356)
	at com.redhat.darcy.webdriver.WebDriverBrowser.lambda$29(WebDriverBrowser.java:317)
	at com.redhat.darcy.webdriver.WebDriverBrowser$$Lambda$64/1060042118.get(Unknown Source)
	at com.redhat.darcy.webdriver.WebDriverBrowser.attemptAndGet(WebDriverBrowser.java:342)
	at com.redhat.darcy.webdriver.WebDriverBrowser.findByView(WebDriverBrowser.java:317)
	at com.redhat.darcy.ui.By$ByView.find(By.java:520)
	at com.redhat.darcy.web.internal.AbstractWebSelection.contextOfType(AbstractWebSelection.java:43)
	at com.redhat.darcy.ui.api.ContextSelection.elementContext(ContextSelection.java:44)
	at com.redhat.darcy.ui.internal.NewContextTransitionEvent.<init>(NewContextTransitionEvent.java:36)
	at com.redhat.darcy.ui.internal.SimpleTransitionEvent.inNewContext(SimpleTransitionEvent.java:57)
	at com.redhat.darcy.ui.internal.SimpleTransitionEvent.inNewContext(SimpleTransitionEvent.java:47)

**Comment by alechenninger** [comment]
This is due to Browser implementing `ElementContext` and `Findable` separately, but not `FindableElementContext` ... which is an unfortunate consequence of Java being Java. In ContextSelection, we need a type that is both `Findable` and a `Context` and so I need to create a separate type for this. So even though `FindableElementContext` is exactly equivalent to a type which implements `Findable` and `ElementContext` ... alas they are not castable in the eyes of Lord Java :).

Quick solution is to make `Browser`s and `Frame`s implement `FindableElementContext`. But this is making me wonder if all `Context`s should be considered `Findable`, so gimme a night to ponder on that.

**Comment by alechenninger** [comment]
As a side note, different inheritance models (like the one that golang uses, which essentially is built in "duck typing" as opposed to explicit inheritance) don't have this problem, for the programming language designer in you :).

**Comment by alechenninger** [comment]
I'm going to mess around with making all `Context`s `Findable` and see if that goes. If I get lost down the rabbit hole I will do the quick but not as clean solution.

**Comment by alechenninger** [comment]
Fixed in #54 

Making all `Context`s `Findable` definitely turned into a bit of a mess :). The webdriver module has a lot of implementations of `Context`s to divide responsibilities and making all of them follow the contract of `Findable` is a little messy... for not much gain, since nothing ever uses that API in those implementations.

**Comment by alechenninger** [comment]
The real fix was here btw https://github.com/darcy-framework/darcy-web/commit/f3b060400702c0c4d7a0e5c31570407cb18c9c18
